import {test} from 'node:test';import assert from 'node:assert/strict';import {buildSync} from 'esbuild';import {chromium} from 'playwright';
import {Course,emptyProgress,chapterActivityKey} from '../shared/model';import {mergedChapterProgress,mergeChapterCourse} from '../shared/chapterMerge';
test('合併保留目標 false／0 設定、來源次單元防線及部分進度',()=>{
 const chapter={title:'',description:'',required:true,threshold:80,opensAt:'',dueAt:'',activities:[]};const c={units:[],chapters:{old:chapter,target:chapter},chapterOrder:['old','target'],chapterOverrides:{A:{old:{required:true,threshold:80},target:{required:false,threshold:0}}}} as unknown as Course;
 const m=mergeChapterCourse(c,'old','target');assert.deepEqual(m.chapterOverrides!.A.target,{required:false,threshold:0});assert.deepEqual(c.chapterOrder,['old','target']);assert.throws(()=>mergeChapterCourse(c,'old','old'));
 const p=emptyProgress();p.activities[chapterActivityKey('old','a')]={position:6,completed:false,updatedAt:3};p.activities[chapterActivityKey('target','a')]={position:8,completed:false,updatedAt:2};const after=mergedChapterProgress(p,'old','target',['a']);assert.deepEqual(after.activities[chapterActivityKey('target','a')],{position:8,completed:false,updatedAt:3});assert.deepEqual(after.activities[chapterActivityKey('old','a')],p.activities[chapterActivityKey('old','a')]);assert.equal(Object.keys(p.activities).length,2);
});
test('單元安排僅空單元可合併、先預覽人數／活動再確認；換目標清空預覽，未保存不得合併',async()=>{
 const bundle=buildSync({entryPoints:['tests/fixtures/chapter-merge.tsx'],bundle:true,write:false,format:'esm',platform:'browser',define:{'import.meta.env':'{}','process.env.NODE_ENV':'"production"'}}).outputFiles[0].text;
 const browser=await chromium.launch({channel:'chrome'});try{const page=await browser.newPage(),errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.route('http://merge.test/',r=>r.fulfill({contentType:'text/html',body:'<div id="root"></div>'}));await page.goto('http://merge.test/');await page.addScriptTag({type:'module',content:bundle});
 const merge=page.getByRole('button',{name:'合併到…',exact:true});await merge.waitFor();assert.equal(await merge.count(),1);await page.getByLabel('課程名稱',{exact:true}).fill('已編輯課程');assert(await merge.isDisabled());await page.getByRole('button',{name:'保存草稿',exact:true}).click();await merge.click();const modal=page.getByRole('dialog');assert.equal(await modal.getByRole('button',{name:/確認合併/}).count(),0);await modal.getByRole('button',{name:'預覽合併',exact:true}).click();await modal.getByText('受影響學生：1 人').waitFor();assert(await modal.getByText('血管教材（a）').isVisible());await modal.getByLabel('合併目標單元').selectOption('淋巴系統');assert.equal(await modal.getByRole('button',{name:/確認合併/}).count(),0);await modal.getByLabel('合併目標單元').selectOption('心臟II');await modal.getByRole('button',{name:'預覽合併',exact:true}).click();await modal.getByRole('button',{name:'確認合併到「心臟II」',exact:true}).click();await modal.waitFor({state:'detached'});assert.equal(await merge.count(),0);assert.equal(await page.locator('.unitmenu').getByText('舊單元',{exact:true}).count(),0);const calls=await page.evaluate(()=>(window as any).mergeTest.calls.filter((c:any)=>c.name==='mergeChapter'));assert.equal(calls.length,3);assert.equal(calls[0].data.preview,true);assert.equal(calls[1].data.preview,true);assert(calls[2].data.confirmationToken);assert.equal(calls[2].data.preview,undefined);assert.deepEqual(errors,[]);
 }finally{await browser.close();}
});
