import { useEffect, useState } from 'react';
import { Course } from '../shared/model';
import { learningMetrics } from '../shared/learning';
import { API } from './service';

function mastery(row: any) {
  const metrics = learningMetrics(row.summary);
  if (!row.nodeTotal || !row.questionTotal) return null;
  return Math.round(40 * Math.min(1, metrics.nodes / row.nodeTotal) + 60 * Math.min(1, metrics.firstCorrect / row.questionTotal));
}

export default function Diagnostics({ course, api, notify }: { course: Course; api: API; notify: (s: string) => void }) {
  const [cl, setCl] = useState(course.classIds[0] || '');
  const [rows, setRows] = useState<any[]>([]), [next, setNext] = useState<string | null>(null), [busy, setBusy] = useState(false), [activity, setActivity] = useState(''), [selected, setSelected] = useState<any>(null);
  useEffect(() => { setRows([]); setNext(null); setSelected(null); }, [cl]);
  const load = async (more = false) => { setBusy(true); try { const r = await api.call('getLearningDiagnostics', { courseId: course.id, classId: cl, after: more ? next : '' }); setRows((old) => more ? [...old, ...r.rows] : r.rows); setNext(r.next); } catch (e) { notify((e as Error).message); } finally { setBusy(false); } };
  const filtered = rows.filter((r) => !activity || `${r.unitId}/${r.activityId}/${r.materialVersion}` === activity);
  return <><header className="pageheading"><div><h1>互動教材學習診斷</h1><p>通關成就與 Mastery 分開呈現；探索、重試與停留是教學線索，不作隱藏評分。</p></div></header><section className="panel"><div className="toolbar"><label>班級<select disabled={busy} value={cl} onChange={(e) => setCl(e.target.value)}>{course.classIds.map((c) => <option key={c} value={c}>{course.classNames?.[c] || c}</option>)}</select></label><label>教材／版本<select value={activity} onChange={(e) => setActivity(e.target.value)}><option value="">全部已載入教材</option>{[...new Set(rows.map((r) => `${r.unitId}/${r.activityId}/${r.materialVersion}`))].map((v) => <option key={v}>{v}</option>)}</select></label><button disabled={busy || !cl} onClick={() => load()}>更新診斷</button></div><p>已載入 {filtered.length} 筆活動紀錄。未回報者不列為零分；YouTube 不納入診斷。</p>{activity && <svg viewBox="0 0 360 250" className="diagnostic-chart" role="img" aria-label="探索比例與首次答對比例分布"><path d="M40 10V210H340 M40 110H340 M190 10V210" fill="none" stroke="currentColor" opacity=".4" /><text x="65" y="240" fill="currentColor">探索比例：0% → 100%</text><text x="45" y="20" fill="currentColor">首次答對比例 ↑</text>{filtered.filter((r) => r.nodeTotal > 0 && r.questionTotal > 0).map((r) => { const m = learningMetrics(r.summary); return <circle key={r.id} cx={40 + 300 * Math.min(1, m.nodes / r.nodeTotal)} cy={210 - 200 * Math.min(1, m.firstCorrect / r.questionTotal)} r="5" fill="var(--blue)"><title>{r.name}：Mastery {mastery(r)}，探索 {m.nodes}，首次答對 {m.firstCorrect}</title></circle>; })}</svg>}<div className="tablewrap"><table><thead><tr><th>學生</th><th>教材／版本</th><th>活動</th><th>探索</th><th>首次答對</th><th>嘗試／重試</th><th>有效時間</th><th>Mastery</th><th>明細</th></tr></thead><tbody>{filtered.map((r) => { const m = learningMetrics(r.summary), score = mastery(r); return <tr key={r.id}><td>{r.name}<small>{r.studentId}</small></td><td>{r.unitId}/{r.activityId} · {r.materialVersion}</td><td>{r.summary.completed ? '已通關' : '探索中'}</td><td>{m.nodes}/{r.nodeTotal || '未設定'}</td><td>{m.firstCorrect}/{r.questionTotal || '未設定'}</td><td>{m.attempts}／{Math.max(0, m.attempts - m.questions)}</td><td>{r.summary.activeSeconds} 秒</td><td>{score === null ? '資料不足' : `${score}%`}</td><td><button onClick={() => setSelected(r)}>查看</button></td></tr>; })}</tbody></table></div>{next && <button disabled={busy} onClick={() => load(true)}>載入更多</button>}<p className="muted">Mastery v1：探索覆蓋 40%＋首次答對比例 60%。重試與逐圖卡停留時間獨立呈現，協助教師判讀，不作正式成績。</p>{selected && <section className="notice"><h2>{selected.name} · {selected.activityId}</h2><p>探索節點：{selected.summary.nodes.join('、') || '尚無'}；使用提示 {selected.summary.hints} 次。</p><p>逐圖卡有效停留：{Object.entries(selected.summary.nodeSeconds || {}).map(([node, seconds]) => `${node} ${seconds} 秒`).join('；') || '尚無'}。</p>{Object.entries(selected.summary.answers).map(([id, q]: [string, any]) => <p key={id}>{id}：首次{q.firstCorrect ? '答對' : '未答對'}，共嘗試 {q.attempts} 次</p>)}<button onClick={() => setSelected(null)}>關閉明細</button></section>}</section></>;
}
